### ISSUE TITLE
using any of the brush hooks leads to a crash inside a create-react-app (typescript)  project

### ISSUE THREAD

**Issue by blurymind** [ascorbic/react-artboard#1]
Here is a playground test project:

I imported everything as was demonstrated in the demo.
Unfortunately its completely unusable since it crashes the moment I call any of the brush hooks.

I am sharing an entire project with the hope that you would be able to help me diagnose the problem here
https://github.com/blurymind/react-pwa-boilerplate

https://github.com/blurymind/react-pwa-boilerplate/blob/main/src/pages/paint/index.tsx

**Comment by blurymind** [comment]
here is the error 
https://reactjs.org/docs/error-decoder.html/?invariant=321

**Comment by blurymind** [comment]
Some things I noticed:

ForwardedRef is a type that doesnt exist in react ^17.0.2
https://github.com/ascorbic/react-artboard/blob/894a406553d8f85438f60070aa25dbe36df27dbd/src/components/Artboard.tsx#L2

in one of your useCallbacks you have put a state setter (setDrawing), which seems wrong
https://github.com/ascorbic/react-artboard/blob/894a406553d8f85438f60070aa25dbe36df27dbd/src/components/Artboard.tsx#L55

but those are probably not whats causing it, im not sure

**Comment by ascorbic** [comment]
Thanks for the report. I was accidentally bundling React, which gave the mismatched version error! If you upgrade it should be fixed (along with the missing `useHistory` export)

**Comment by blurymind** [comment]
thank you for fixing this :) I will give it a test again tonight :+1: :tada:
